import { Weapon, WeaponType } from '../types/game';

export const WEAPON_DEFINITIONS: Record<
  WeaponType,
  Omit<Weapon, 'id' | 'perks'>
> = {
  blaster: {
    name: 'Blaster',
    type: 'blaster',
    damage: 10,
    fireRate: 0.2,
    projectileSpeed: 12,
    projectileSize: 6,
    spread: 0.05,
    projectileCount: 1,
    piercing: false,
    color: '#00ffff',
    firingMode: 'auto',
    cooldown: 0,
    description: 'Rapid-fire energy weapon',
    maxRange: 480,
  },
  shotgun: {
    name: 'Shotgun',
    type: 'shotgun',
    damage: 5,
    fireRate: 0.6,
    projectileSpeed: 10,
    projectileSize: 5,
    spread: 0.2,
    projectileCount: 5,
    piercing: false,
    color: '#ff6600',
    firingMode: 'manual',
    cooldown: 0,
    description: 'Close-range spread weapon',
    maxRange: 160,
  },
  laser: {
    name: 'Laser',
    type: 'laser',
    damage: 16,
    fireRate: 0.15,
    projectileSpeed: 18,
    projectileSize: 4,
    spread: 0,
    projectileCount: 1,
    piercing: true,
    color: '#ff00ff',
    firingMode: 'auto',
    cooldown: 0,
    description: 'High-speed piercing laser',
    maxRange: 520,
  },
  missile: {
    name: 'Missile',
    type: 'missile',
    damage: 25,
    fireRate: 0.8,
    projectileSpeed: 8,
    projectileSize: 10,
    spread: 0.1,
    projectileCount: 1,
    piercing: false,
    color: '#ff0000',
    firingMode: 'manual',
    cooldown: 0,
    description: 'Heavy explosive projectile',
    explosive: true,
    explosionRadius: 50,
    maxRange: 480,
  },
  railgun: {
    name: 'Railgun',
    type: 'railgun',
    damage: 100,
    fireRate: 1.2,
    projectileSpeed: 25,
    projectileSize: 8,
    spread: 0,
    projectileCount: 1,
    piercing: true,
    color: '#00ff00',
    firingMode: 'charge',
    cooldown: 0,
    description: 'Charge to fire devastating beam',
    chargeTime: 1.5,
    currentCharge: 0,
    isCharging: false,
    maxRange: 700,
  },
  flamethrower: {
    name: 'Flamethrower',
    type: 'flamethrower',
    damage: 4,
    fireRate: 0.08,
    projectileSpeed: 8,
    projectileSize: 7,
    spread: 0.15,
    projectileCount: 3,
    piercing: false,
    color: '#ff6600',
    firingMode: 'auto',
    cooldown: 0,
    description: 'Short-range continuous fire',
    maxRange: 120,
  },
  arc_cannon: {
    name: 'Arc Cannon',
    type: 'arc_cannon',
    damage: 14,
    fireRate: 0.4,
    projectileSpeed: 14,
    projectileSize: 6,
    spread: 0.1,
    projectileCount: 1,
    piercing: false,
    color: '#00ccff',
    firingMode: 'manual',
    cooldown: 0,
    description: 'Electric discharge weapon',
    homing: true,
    homingStrength: 0.05,
    maxRange: 480,
  },
  gravity_well: {
    name: 'Gravity Well',
    type: 'gravity_well',
    damage: 22,
    fireRate: 1.0,
    projectileSpeed: 6,
    projectileSize: 15,
    spread: 0,
    projectileCount: 1,
    piercing: false,
    color: '#9933ff',
    firingMode: 'manual',
    cooldown: 0,
    description: 'Slow-moving gravitational bomb',
    explosive: true,
    explosionRadius: 80,
    maxRange: 400,
  },
  shuriken_launcher: {
    name: 'Shuriken Launcher',
    type: 'shuriken_launcher',
    damage: 12,
    fireRate: 0.3,
    projectileSpeed: 16,
    projectileSize: 5,
    spread: 0.08,
    projectileCount: 3,
    piercing: false,
    color: '#cccccc',
    firingMode: 'manual',
    cooldown: 0,
    description: 'Multi-projectile throwing weapon',
    ricochet: true,
    maxRange: 440,
  },
  beam_laser: {
    name: 'Beam Laser',
    type: 'beam_laser',
    damage: 10,
    fireRate: 0.05,
    projectileSpeed: 30,
    projectileSize: 3,
    spread: 0,
    projectileCount: 1,
    piercing: true,
    color: '#ff33cc',
    firingMode: 'beam',
    cooldown: 0,
    description: 'Continuous beam that overheats',
    beamDuration: 3.0,
    beamCooldown: 2.0,
    isBeaming: false,
    beamTimer: 0,
    maxRange: 480,
    beamHeat: 0,
    beamMaxHeat: 100,
    beamOverheated: false,
  },
  charge_cannon: {
    name: 'Charge Cannon',
    type: 'charge_cannon',
    damage: 55,
    fireRate: 0.5,
    projectileSpeed: 15,
    projectileSize: 12,
    spread: 0,
    projectileCount: 1,
    piercing: false,
    color: '#ffff00',
    firingMode: 'charge',
    cooldown: 0,
    description: 'Charge for massive damage',
    chargeTime: 2.0,
    currentCharge: 0,
    isCharging: false,
    maxRange: 520,
  },
  grappling_hook: {
    name: 'Grappling Hook',
    type: 'grappling_hook',
    damage: 0,
    fireRate: 1.2,
    projectileSpeed: 20,
    projectileSize: 8,
    spread: 0,
    projectileCount: 1,
    piercing: false,
    color: '#888888',
    firingMode: 'manual',
    cooldown: 0,
    description: 'Hook onto enemies or obstacles to pull yourself',
    maxRange: 400,
    grapplingStats: {
      maxRange: 400,
      cooldown: 1.2,
      pullSpeed: 10,
      slamDamage: 0,
      slamRadius: 0,
      attachBonus: 0,
    },
  },
  void_blade: {
    name: 'Void Blade',
    type: 'void_blade',
    damage: 35,
    fireRate: 0.4,
    projectileSpeed: 0,
    projectileSize: 0,
    spread: 0,
    projectileCount: 0,
    piercing: false,
    color: '#9333ea',
    firingMode: 'manual',
    cooldown: 0,
    description: 'Devastating melee strikes with combo potential',
    maxRange: 80,
    meleeStats: {
      range: 80,
      swingDuration: 0.5,
      swingAngle: 90,
      comboCount: 3,
      comboDamageMultiplier: 1.5,
      dashSlashBonus: 2.0,
    },
    isSwinging: false,
    swingTimer: 0,
    comboCounter: 0,
    comboResetTimer: 0,
    meleeFormId: 'void_form',
  },
  crimson_scythe: {
    name: 'Crimson Scythe',
    type: 'crimson_scythe',
    damage: 28,
    fireRate: 0.25,
    projectileSpeed: 0,
    projectileSize: 0,
    spread: 0,
    projectileCount: 0,
    piercing: false,
    color: '#dc2626',
    firingMode: 'manual',
    cooldown: 0,
    description: 'Rapid slashing strikes that steal life',
    maxRange: 85,
    meleeStats: {
      range: 85,
      swingDuration: 0.375,
      swingAngle: 100,
      comboCount: 3,
      comboDamageMultiplier: 1.4,
      dashSlashBonus: 1.8,
    },
    isSwinging: false,
    swingTimer: 0,
    comboCounter: 0,
    comboResetTimer: 0,
    meleeFormId: 'rapid_form',
  },
  titan_hammer: {
    name: 'Titan Hammer',
    type: 'titan_hammer',
    damage: 55,
    fireRate: 0.8,
    projectileSpeed: 0,
    projectileSize: 0,
    spread: 0,
    projectileCount: 0,
    piercing: false,
    color: '#78716c',
    firingMode: 'manual',
    cooldown: 0,
    description: 'Crushing blows that shatter enemies',
    maxRange: 70,
    meleeStats: {
      range: 70,
      swingDuration: 0.75,
      swingAngle: 80,
      comboCount: 3,
      comboDamageMultiplier: 2.0,
      dashSlashBonus: 2.5,
    },
    isSwinging: false,
    swingTimer: 0,
    comboCounter: 0,
    comboResetTimer: 0,
    meleeFormId: 'heavy_form',
  },
  flowing_glaive: {
    name: 'Flowing Glaive',
    type: 'flowing_glaive',
    damage: 32,
    fireRate: 0.45,
    projectileSpeed: 0,
    projectileSize: 0,
    spread: 0,
    projectileCount: 0,
    piercing: false,
    color: '#06b6d4',
    firingMode: 'manual',
    cooldown: 0,
    description: 'Wide sweeping attacks with extended reach',
    maxRange: 95,
    meleeStats: {
      range: 95,
      swingDuration: 0.55,
      swingAngle: 120,
      comboCount: 3,
      comboDamageMultiplier: 1.6,
      dashSlashBonus: 2.2,
    },
    isSwinging: false,
    swingTimer: 0,
    comboCounter: 0,
    comboResetTimer: 0,
    meleeFormId: 'flowing_form',
  },
  shadow_daggers: {
    name: 'Shadow Daggers',
    type: 'shadow_daggers',
    damage: 22,
    fireRate: 0.2,
    projectileSpeed: 0,
    projectileSize: 0,
    spread: 0,
    projectileCount: 0,
    piercing: false,
    color: '#6366f1',
    firingMode: 'manual',
    cooldown: 0,
    description: 'Precise strikes from the shadows',
    maxRange: 60,
    meleeStats: {
      range: 60,
      swingDuration: 0.375,
      swingAngle: 60,
      comboCount: 3,
      comboDamageMultiplier: 2.0,
      dashSlashBonus: 3.0,
    },
    isSwinging: false,
    swingTimer: 0,
    comboCounter: 0,
    comboResetTimer: 0,
    meleeFormId: 'assassin_form',
  },
  berserker_axe: {
    name: 'Berserker Axe',
    type: 'berserker_axe',
    damage: 45,
    fireRate: 0.5,
    projectileSpeed: 0,
    projectileSize: 0,
    spread: 0,
    projectileCount: 0,
    piercing: false,
    color: '#ef4444',
    firingMode: 'manual',
    cooldown: 0,
    description: 'Wild, devastating swings fueled by rage',
    maxRange: 75,
    meleeStats: {
      range: 75,
      swingDuration: 0.625,
      swingAngle: 110,
      comboCount: 4,
      comboDamageMultiplier: 1.8,
      dashSlashBonus: 2.3,
    },
    isSwinging: false,
    swingTimer: 0,
    comboCounter: 0,
    comboResetTimer: 0,
    meleeFormId: 'berserker_form',
  },
  guardian_blade: {
    name: 'Guardian Blade',
    type: 'guardian_blade',
    damage: 30,
    fireRate: 0.5,
    projectileSpeed: 0,
    projectileSize: 0,
    spread: 0,
    projectileCount: 0,
    piercing: false,
    color: '#fbbf24',
    firingMode: 'manual',
    cooldown: 0,
    description: 'Defensive strikes that protect and counter',
    maxRange: 72,
    meleeStats: {
      range: 72,
      swingDuration: 0.5,
      swingAngle: 100,
      comboCount: 3,
      comboDamageMultiplier: 1.5,
      dashSlashBonus: 2.0,
    },
    isSwinging: false,
    swingTimer: 0,
    comboCounter: 0,
    comboResetTimer: 0,
    meleeFormId: 'guardian_form',
  },
};
